### ISSUE TITLE
Pull request creation

### ISSUE THREAD

**Issue by pazka** [ahmadyazdanii/bind-record-manager#1]
Hi, 

I wanted to bring changes to your library in the form of a pull request but the current rights doesn't allow me to push a new branch. 

Is there a way that you could authorize that ?

**Comment by ahmadyazdanii** [comment]
Hi @pazka , you must fork first and clone project, create new branch from master and commit, push changes in the branch and the end of create pull request for me :) 
it's a public repository then you can create pull request.

**Comment by pazka** [comment]
I'll try that, thanks !
